name             'chef_cassandra_mesos'
maintainer       'Charles Yan'
maintainer_email 'charlesxyan@gmail.com'
license          'All rights reserved'
description      'Installs/Configures chef_cassandra_mesos'
long_description 'Installs/Configures chef_cassandra_mesos'
version          '0.1.0'
